spring:
  application:
    name: cyj-rules
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:

    # 仅支持 http/https，不限定响应内容格式
    remote:
      # 只订阅非adguard官方已包含的第三方规则
      - name: AWAvenue-Adblock-Rule
        path: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Adblock-Rule/main/AWAvenue-Adblock-Rule.txt
      - name: halflife-list
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad.txt
      - name: ADgk-baidu
        path: https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt
      - name: DD-AD
        path: https://raw.githubusercontent.com/afwfv/DD-AD/main/rule/DD-AD.txt
      # 以下是host规则，尽量全部订阅以去重
      # - name: AdAway Default Blocklist
      #   path: https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
       # 此规则已包含上面1条
      - name: StevenBlack
        path: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
        # path: https://raw.githubusercontent.com/dead-hosts/hosts_git_StevenBlack/master/output/origin.list/domains/ACTIVE/list
      # - name: yhosts
      #   path: https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts.txt
      # - name: 1024_hosts
      #   path: https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts
      # - name: QuarkList
      #   path: https://raw.githubusercontent.com/francis-zhao/quarklist/master/dist/hosts
      # - name: ilpl
      #   path: https://raw.githubusercontent.com/ilpl/ad-hosts/master/hosts
      # 此规则已包含上面4条
      - name: 小贝塔
        path: https://raw.githubusercontent.com/rentianyu/Ad-set-hosts/master/host
      # - name: WindowsSpyBlocker
      #   path: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      # 此规则已包含上面1条
      # - name: anti-AD
      #   path: https://raw.githubusercontent.com/neodevpro/neodevhost/master/adblocker
      # - name: 大圣净化
      #   path: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
      # 此规则已包含上面2条
      - name: neodevpro
        path: https://raw.githubusercontent.com/neodevpro/neodevhost/master/domain
      - name: AdRules
        path: https://raw.githubusercontent.com/Cats-Team/AdRules/main/ad-domains.txt


    #本地规则请将文件放置到项目路径rule目录中
    local:
#      - name: 'local rule'
#        path: 'local-rule.txt'
  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [CYJ Adblock List]
      ! Title: CYJ Adblock List ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/YujiaCheng1996/ad-filters/
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      filters.txt:
        - REGEX
        - MODIFY
      dns.txt:
        - DOMAIN
        - REGEX
      agh.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
